'\" t
.\" -*- nroff -*-
.\"nr pp:debug 0
.ie '\n[.fam]'M' .ds HF GB
.el              .ds HF HB
.
.TH SAMPLE 7
.\"ss 12
.ds dg "\v[-0.4m]\s-3\[dg]\s+3\v[+0.4m]\""
.ds dd "\v[-0.4m]\s-3\[dd]\s+3\v[+0.4m]\""
.ds dg "\v[-0.4m]\s-3\f(MR†\fP\s+3\v[+0.4m]\""
.ds dd "\v[-0.4m]\s-3\f(MR‡\fP\s+3\v[+0.4m]\""
.ds la \[u3008]
.ds ra \[u3009]
.\"ds C` \s-1
.\"ds C' \s+1
.\"char \(bu *
.ds TeX T\h'-.2m'\v'.2m'E\v'-.2m'\h'-.1m'X\" Knuth's TeX
.
.ds emsp \m[red]\D'l 0 0.1'\D'l 1 0'\D'l 0 -0.6'\D'l -1 0'\D'l 0 0.5'\h'1'\m[]
.ds ensp \m[red]\D'l 0 0.1'\D'l 0.5 0'\D'l 0 -0.6'\D'l -0.5 0'\D'l 0 0.5'\h'0.5'\m[]
.ds qwsp \m[red]\D'l 0 0.1'\D'l 0.25 0'\D'l 0 -0.6'\D'l -0.25 0'\D'l 0 0.5'\h'0.25'\m[]
.ds zwsp \m[red]\D'l 0 0.1'\D'l 0.1 0'\D'l 0 -0.6'\D'l -0.1 0'\D'l 0 0.5'\h'0.1'\m[]
.
.\".ig ..
.am1 EX
.sp 0.2
.nr VS_BAK \\n[VS]
.nr VS (\\n[PS] * 120 / 100)
.vs \\n[VS]u
.ps -1
..
.am1 EE
.nr VS \\n[VS_BAK]
.vs \\n[VS]u
.ps
..
.\"...
.
.\" ------------------------------------------------------------------
.SH NAME
.\" ------------------------------------------------------------------
.
sample \- Groff と日本語
.
.\" ------------------------------------------------------------------
.SH SYNOPSYS
.\" ------------------------------------------------------------------
.
.EX
groff -k -mandoc -mja ./sample.7 >a.ps
.EE
.
.\" ------------------------------------------------------------------
.SH DESCRIPTION
.\" ------------------------------------------------------------------
.
.\" ------------------------------------------------------------------
.SS 日本語マンページのメモ
.\" ------------------------------------------------------------------
.
FreeBSDの日本語のマンページgroff(7)に次のようなメモがあります。
.
.PP
.EX
\&.\e" nroff の justification をオフにする. justification は, 日本語に似合わない.\""
\&.na
\&.\e" ハイフネーションをオフにする.\""
\&.hy 0
.EE
.
.\" ------------------------------------------------------------------
.SS 両端揃え（justification）を確かめる
.\" ------------------------------------------------------------------
.
.PP
確認に使用する日本語のマンページを選び、\f(CW\*(C`na\*(C'\fP と
\f(CW\*(C`hy 0\*(C'\fP がnroffでしか働かないようにします。
.
.PP
.EX
\&.if n .na
\&.if n .hy 0
.EE
.
.PP
このような設定は、debianの
.UR https://manpages.debian.org/buster/manpages-ja/groff.7.ja.html
groff(7)の日本語のマンページ
.UE \c
.
にはありません。ubuntuでは \f(CW\*(C`ad l\*(C'\fP が使われています。様々です。
.
.PP
日本語のマンページを修正し、そのpsかpdf出力を確認します。groffは両端揃
えでスペースを補正（伸長）するので、補正対象が少ないとき、個々のスペー
スの補正量が大きくなります。
.
.
.\" ------------------------------------------------------------------
.SS 前処理プログラム prepro を使う
.\" ------------------------------------------------------------------
.
一つのスペースに割り当てられる補正量を小さくするため、文中のスペースを
増やします。
.
字間に幅ゼロのスペースを挟んだり、字体にスペースを含む "、" （テン）や
"。" （マル）のような約物をプロポーショナルフォントとスペースの組合せ
に直します。
.
.PP
入力の機械的な修正にはtroffの前処理プログラムを利用します。troffの前処
理プログラムはDESCファイルのprepro行で指定します。prepro行は
.BR groff_font (5)
に説明されていますが、詳細は分りません。groff \-Vの出力（下記）が参考
になります。
.
.PP
.EX
\&$ \fBgroff -V -Tpdf -mandoc -mja -k files...\fP
\&preconv files... | \fIprepro\fP troff -mandoc -mja -Tpdf | \fIpostpro\fP
.EE
.
.PP
.IP 1. 4
\fIprepro\fP と \fIpostpro\fP はデバイスのDESCファイルで指定します。
preconvはgroffのオプション \-kの他、\-Dや \-Kを指定したときに使われま
す。
.
.IP 2.
\fIprepro\fP の入力はtroffのコマンドライン（\fIprepro\fP のコマンドラ
インの troff 以降）に指定されるtroffの入力ファイルか、標準入力（前処理
プログラムの出力）です。
.
.IP 3.
\fIprepro\fP の出力はtroffの標準入力になるので、troffのコマンドライン
に入力ファイルが指定されていれば取り除かなければなりません。
.
.\" ------------------------------------------------------------------
.SS スペースを作る
.\" ------------------------------------------------------------------
.
伸びるスペースを作ります。groffのスペースは、伸び縮みする \*[TeX] の
glueとは違い、伸びるだけで縮みません。
.
.PP
.EX
\&.de pp:sp
\e\ec
\&.  ie \e\en[.$] .ss \e\e$*
\&.  el .ss \e\en[\e\e$0-width]
\&.  nop \e\e& \e\ec
\&.  ss
\&..
\&.nr pp:emsp-width  (\en[.ss] * 4)
\&.nr pp:hemsp-width (\en[.ss] * 2)
\&.nr pp:qemsp-width (\en[.ss])
.\"\&.nr pp:wdsp-width  \en[.ss]
.\"\&.nr pp:nrsp-width  (\en[.ss] / 4)
\&.nr pp:zwsp-width  0
\&.
\&.als pp:emsp  pp:sp
\&.als pp:hemsp pp:sp
\&.als pp:qemsp pp:sp
.\"\&.als pp:wdsp  pp:sp
.\"\&.als pp:nrsp  pp:sp
\&.als pp:zwsp  pp:sp
.EE
.
.PP
このマクロは
.UR https://www.gnu.org/software/groff/manual/html_node/Strings.html#index-_005c_002a
\f(CW\*(C`\e*\*(C'\fP
.UE
で実行します。
.
スペースの幅は、引数で指定するか、マクロ名で決まります。
.PP
.RS 2
.PD 0
.TP 20
引数で幅を指定する:
.
\f(CW\*(C`\e*[pp:sp\*(C'\fP \f(CI\*(C`width\*(C'\fP\f(CW\*(C`]\*(C'\fP
.TP
名前で幅が決まる:
.
\f(CW\*(C`\e*[pp:emsp ]\*(C'\fP, \f(CW\*(C`\e*[pp:hemsp ]\*(C'\fP,
\f(CW\*(C`\e*[pp:qemsp ]\*(C'\fP, \f(CW\*(C`\e*[pp:zwsp ]\*(C'\fP, ...
.PD
.RE
.
.PP
名前で幅が決まるマクロは、そのマクロ名に -width を付けた数値レジスタに
あらかじめ幅を設定しておく必要があります。
.
.PP
マクロを \f(CW\*(C`\e*\*(C'\fP で実行するのは、文中にマクロ（スペース）を追加
しても行数を変えないようにするためです。行数が変わるとgroffのメッセー
ジで示される行番号が変わります。引数の入力に
.
.UR https://www.gnu.org/software/groff/manual/html_node/Input-Line-Traps.html#index-it
\f(CW\*(C`it\*(C'\fP
.UE
を使うマクロは \ec で終わる行も数えるので、
スペースが挿入されるところに改行も追加されたように見えるかもしれません。
.
.PP
.UR https://git.savannah.gnu.org/cgit/groff.git/tree/ChangeLog?h=1.22.4#n1519
groff 1.22.4 の ChangeLog
.UE
で新しいgroffは \f(CW\*(C`it\*(C'\fP の代りに \f(CW\*(C`itc\*(C'\fP を
使うことが分ります。
.
詳細は
.UR https://savannah.gnu.org/bugs/?42907
bug #42907
.UE
から辿れます。
.
.\" ------------------------------------------------------------------
.SS スペースの大きさ
.\" ------------------------------------------------------------------
.
伸びるスペース \*[ensp] は20Hで作ります。
.
その大きさ（幅）はフォントのspacewidthとssリクエストのワードスペースサ
イズで決まります。
.
.TS
tab(;);
l l l.
\f(TRT Times\fP;\(->|\f(TR \fP|\(<-;\f(CW\ew'\ef(TR \efP'\fP = \w'\f(TR \fP'u
\f(HRH Helvetica\fP;\(->|\f(HR \fP|\(<-;\f(CW\ew'\ef(HR \efP'\fP = \w'\f(HR \fP'u
\f(CRC Courier\fP;\(->|\f(CR \fP|\(<-;\f(CW\ew'\ef(CR \efP'\fP = \w'\f(CR \fP'u
.TE
.
.PP
そのため日本語のスペースの調整に
ss でワードスペースサイズを設定するとき、
.ig
\f(CW(\ew'\ef(TR \efP' ÷ \ew' ')\fP
.
を乗じて、
..
使われている欧文フォントのスペースの大きさの違いによる影響を
回避する必要があります。
.
.
.PP
.ne 4
次の例は、約物の字体に含まれるスペースの大きさが、そのとき使われている
欧文フォントの影響を受けないこと、また等幅フォントで連続する約物を詰め
ないことを確かめます。
.
.nr pp:debug.bak \n[pp:debug]
.nr pp:debug 1
.PP
.PD 0
.
.ds mF \n[.fam]
.nr mE \n(.f
.
.fam T
.ft \n[.fam]R
.
.TP 12m
\&.fn=\n[.fn] \&.f=\n[.f] \&.fam=\n[.fam]
■、■、■、■、■、■、、（連続する約物）詰める
.
.fam H
.ft \n[.fam]R
.TP
\&.fn=\n[.fn] \&.f=\n[.f] \&.fam=\n[.fam]
■、■、■、■、■、■、、（連続する約物）詰める
.
.fam C
.ft \n[.fam]R
.TP
\&.fn=\n[.fn] \&.f=\n[.f] \&.fam=\n[.fam]
■、■、■、■、■、■、。（連続する約物）詰めない
.
.fam \*(mF
.ft \n(mE
.PD
.nr pp:debug \n[pp:debug.bak]
.
.\" ------------------------------------------------------------------
.SS スペースを配置する
.\" ------------------------------------------------------------------
.
日本語の字間に幅ゼロのスペース \*[zwsp] を配置します。
.
.PP
.IP \(bu 4
「おはよう」 \(-> 「お\*[zwsp]は\*[zwsp]よ\*[zwsp]う」
.
.PP
約物の字体に含まれるスペースを取り除き、代りにスペース \*[ensp] を補い
ます。
.
.PP
.PD 0.1
.IP \(bu 4
「\z。\h'1m'」 \(-> 「。\&\*[ensp]」
.IP \(bu
「\z、\h'1m'」 \(-> 「、\&\*[ensp]」
.IP \(bu
「\Z'\h[0.5m]（'\h'1m'」 \(-> 「\*[ensp]\&（」
.IP \(bu
「\z）\h'1m'」 \(-> 「）\&\*[ensp]」
.IP \(bu
「\Z'\h[0.25m]・'\h'1m'」 \(-> 「\*[qwsp]\&・\&\*[qwsp]」
.PD
.
.PP
それから、日本語と欧文の境界にスペースを配置します。preproは、
.UR https://qiita.com/CodeOne/items/43d2b8e4247b020652b2
日本語文章中、英単語の両端にスペースをつける人
.UE \c
.
のようにスペースをつけます。スペースをつける人のスペース（入力されたス
ペース）はそのまま残します。人が入力するスペースには20Hの他、groffのエ
スケープで作られたものもあります。
.
.PP
数は日本語と近いと考えられるので（説明は上のリンクを参照）、数と日本語
の境界のスペースを狭くします。
.
また数を構成するものには数字だけでなく前置記号（￥、＄、￡、等）、後置
記号（℃、％、㌔、等）、更に単位もあると思います。
.
分り難いと思われるので、
文中に次の行を置くことで追加したスペースを確認できるようにしています。
.
.PP
.EX
\&.nr pp:debug 1
.EE
.
.PP
.nr pp:debug.bak \n[pp:debug]
.nr pp:debug 1
.PD 0
.IP \(bu 4
2012年3月4日は今日と同じ曜日ですか？
.IP \(bu
弟から1,000円もらう。1,\|000円、1,\~000円など
.IP \(bu
数は単位も含みます。縦横230㎝や重さ4.75㌢は単位の後にスペースが入ります。
.IP \(bu
単位は英字の組合せも受け入れます。従って230cmと書くことができます。
.IP \(bu
単位230km/hや4.75kg/m\s-3\u2\d\s+3はパースできません。
.IP \(bu
単位230[km/h]や4.75(kg/m\s-3\u2\d\s+3)はパースできます。
.PD
.PP
桁を区切るカンマの後、括弧の前後のスペースの調整は難しいので、何もしていません。
.nr pp:debug \n[pp:debug.bak]
.
.PP
それから、分離禁止文字の前後で語や数のために機械的に追加したスペースを
取り除くとき、約物の字体に含まれるスペースを取り除かないようにします。
（まだできないことを書く）
.
.
.\" ------------------------------------------------------------------
.SS 連続する約物の配置
.\" ------------------------------------------------------------------
.
.UR https://www.w3.org/TR/jlreq/
日本語組版処理の要件 （日本語版） W3C 技術ノート
.UE
.
「3.1.4 始め括弧類，終わり括弧類，読点類，句点類及び中点類が連続する場
合の配置方法」を参考にしました。例を示します。
.
.PP
.PD 0
.IP \[u2460]  4
句読点の後ろに終わり括弧類が連続
.br
…である。」この…
.
.IP \[u2461]  4
終わり括弧類の後ろに句読点が連続
.br
…である）。この…
.
.IP \[u2462]  4
読点類の後ろに始め括弧類が連続
.br
…である、「この…
.
.IP \[u2463]  4
終わり括弧類の後ろに始め括弧類が連続
.br
…である」「この…
.
.IP \[u2464]  4
始め括弧類の後ろに始め括弧類が連続
.br
…である「『この…
.
.IP \[u2465]  4
終わり括弧類の後ろに終わり括弧類が連続
.br
…である）」この…
.
.IP \[u2466]  4
括弧類と中点類が連続
.br
…「編集」・「校正」…
.PD
.
.PP
（後で）禁則ではスペースのマクロに使われる20Hを \f(CW\*(C`\e~\*(C'\fP にする必
要があります。
.
.ig
.PP
.UR https://www.gnu.org/software/groff/manual/html_node/Ligatures-and-Kerning.html
Ligatures and Kerning
.UE
も試しましたが、日本語の約物には使えませんでした。確かunicodeの文字に
は使えない、といった類のエラーが出力されました。
..
.
.\" ------------------------------------------------------------------
.SS プロポーショナルフォント（もどき）を作る
.\" ------------------------------------------------------------------
.
サンプルのps.localの一部を示します。
.
.PP
.EX
\&.\e" A.6 Full stops (cl-06)\""
\&.if (\ew'\e[u3002]' > 0.8m) .char \e[u3002] \e[u3002]\eh'-0.5m'\e" 。\""
\&.if (\ew'\e[uFF0E]' > 0.8m) .char \e[uFF0E] \e[uFF0E]\eh'-0.5m'\e" ．\""
.EE
.
.PP
以下、字体の幅が0.5em以下で「青」、そうでないとき「赤」です。（大半は
青の筈です。）
.
.de check_char
.  nop \m[grey]|\m[]\c
.  ie (\w'\\$1' <= 0.5m) .nop \m[blue]\\$1\m[]\c
.  el .nop \m[red]\\$1\m[]\c
..
.de check_w3c_jlreq_a1-7
.PD 0
.TP 3i
A.1 Opening brackets (cl-01)
.check_char ‘
.check_char “
.check_char (
.check_char （
.check_char 〔
.check_char [
.check_char ［
.check_char {
.check_char ｛
.check_char 〈
.check_char 《
.check_char 「
.check_char 『
.check_char 【
.check_char ⦅
.check_char ｟
.check_char 〘
.check_char 〖
.check_char «
.check_char 〝
.check_char
.
.TP
A.2 Closing brackets (cl-02)
.check_char ’
.check_char ”
.check_char )
.check_char ）
.check_char 〕
.check_char ]
.check_char ］
.check_char }
.check_char ｝
.check_char 〉
.check_char 》
.check_char 」
.check_char 』
.check_char 】
.check_char ⦆
.check_char ｠
.check_char 〙
.check_char 〗
.check_char »
.check_char 〟
.check_char
.
.TP
A.3 Hyphens (cl-03)
.check_char ‐
.\"check_char 〜
.check_char ゠
.check_char –
.check_char
.
.TP
A.4 Dividing punctuation marks (cl-04)
.check_char !
.check_char ！
.check_char ?
.check_char ？
.\"check_char ‼
.\"check_char ⁇
.\"check_char ⁈
.\"check_char ⁉
.check_char
.
.TP
A.5 Middle dots (cl-05)
.check_char ・
.check_char ：
.check_char :
.check_char ;
.check_char
.
.TP
A.6 Full stops (cl-06)
.check_char 。
.check_char ．
.check_char .
.check_char 
.
.TP
A.7 Commas (cl-07)
.check_char 、
.check_char ，
.check_char ,
.check_char
.PD
..
.
.PP
.check_w3c_jlreq_a1-7
.
.
.PP
フォントをインストールするとき、スタイル I B BI は必要に応じて
fontforgeで作成するので少し時間がかかります。
.
.PP
.EX
\&$ make -f font-sauce.mk install
.EE
.
.PP
以下の \&.mk があります。
.
.PP
.PD 0
.IP \(bu 4
.UR https://github.com/3846masa/sauce-han-fonts
醤ノ明朝
.UE
（font-sauce.mk）
.IP \(bu
.UR https://github.com/ButTaiwan/genyo-font
源様明朝
.UE
（font-genyo.mk）
.IP \(bu
.UR https://moji.or.jp/ipafont/
IPAex明朝
.UE
（font-ipaex.mk）
.IP \(bu
.UR https://moji.or.jp/ipafont/
Takao明朝
.UE
（font-takao.mk）
.PD
.
.ig
.PP
fontforgeを止めるために、
.UR https://github.com/obuk/use-groff/issues/1
イタリック体をPostScript文法で
.UE \c
ヒントを頂きました。しかし、ttfからafmを出力する、グリフ名をAdobe
Glyph Listに直す、でもfontforgeを使用しているため、止めるのは難しそう
です。
..
.
.\" ------------------------------------------------------------------
.SS unicodeの正規化を抑止する
.\" ------------------------------------------------------------------
.
groffはCJK互換漢字 F900-FAFF、CJK互換漢字補助 2F800-2FA1Fを正規化しま
す。正規化は、たとえば、「視（\e[u8996]）」の旧字「視（\e[uFA61]）」
を「視（\e[u8996]）」にします。
.
.PP
旧字を使うにはgroffのリポジトリを取得し、
\%src/\:utils/\:afmtodit/\:afmtodit.tablesと
\%src/\:libs/\:libgroff/\:uniuni.cppを修正し、
groffをリビルドする必要があります。
.
.ig
.PP
groffのリビルドには抵抗があったので、先に次のようにCJK互換漢字を異体字
で定義できないか試しましたが、正規化を回避することはできませんでした。
.
.sp 0.5
.EX
\&.char \e[uFA61] \e[u8996_E0101]
.EE
..
.\" ------------------------------------------------------------------
.SS 異体字を使う
.\" ------------------------------------------------------------------
.
.PP
groffで異体字を扱うには、
.UR https://docs.microsoft.com/en-us/typography/opentype/spec/cmap
Character to Glyph Index Mapping Table (cmap)
.UE
のUVSからtextmapを作成し、
.BR afmtodit (1)
に入力して異体字をサポートするgroffのフォントを作成する必要があります。
.
.PP
異体字はフォントに依存します。「視（\e[u8996]）」とその異体字に関する
部分をいくつかのフォントで示します。
.
.TP
SauceHanSerifJP-Regular
.ta 8m +8m +8m +8m +8m +8m
.EX
u8996	1000,836,79	2	14709	uni8996
u8996_E0100	\[dq]
uFA61	1000,818,77	2	18188	uniFA61
u8996_FE00	\[dq]
u8996_E0101	\[dq]
.EE
.
.TP
GenYoMinJP-Regular
.EX
u8996	1000,836,79	2	25966	uni8996
uFA61	1000,818,77	2	32113	uniFA61
.EE
.
.TP
IPAexMincho-Regular
.EX
u8996	1000,827,74	2	9762	uni8996
uFA61	1000,812,72	2	12093	uniFA61
u8996_FE00	\[dq]
.EE
.
.PP
これを見る限り異体字はフォントごと異なることが分ります。できるだけ使用
しないでおくか、もし使うなら変更の可能性を考慮して使うのが良さそうです。
.
.PP
上のSauceHanSerifJP-Regularを見ると、「視（\f(CW\e[uFA61]\fP）」には異
体字セレクタ（Variation Selector）を用いた表現 \f(CW\e[u8996_FE00]\fP
と \f(CW\e[u8996_E0101]\fP があります。
.
.PP
旧字「\f(CW\e[u8996_E0101]\fP」は「旧字である」ということを明示するた
めに独立したVSを後に添えて「\f(CW\[u8996]\e[uE0101]\fP」と表現する方が
分りやすい場合もありそうです。
.
.TS
tab(;);
lfCW l l l.
.ig ..
\e[u9089_E0101];邉󠄁;邉\[uE0101];\[u9089_E0101];
\e[u9089_E0102];邉󠄂;邉\[uE0102];\[u9089_E0102];
\e[u9089_E0103];邉󠄃;邉\[uE0103];\[u9089_E0103];
\e[u9089_E0104];邉󠄄;邉\[uE0104];\[u9089_E0104];
\e[u9089_E0105];邉󠄅;邉\[uE0105];\[u9089_E0105];
\e[u9089_E0106];邉󠄆;邉\[uE0106];\[u9089_E0106];
\e[u9089_E0107];邉󠄇;邉\[uE0107];\[u9089_E0107];
\e[u9089_E0108];邉󠄈;邉\[uE0108];\[u9089_E0108];
\e[u9089_E0109];邉󠄉;邉\[uE0109];\[u9089_E0109];
\e[u9089_E010A];邉󠄊;邉\[uE010A];\[u9089_E010A];
\e[u9089_E010B];邉󠄋;邉\[uE010B];\[u9089_E010B];
\e[u9089_E010C];邉󠄌;邉\[uE010C];\[u9089_E010C];
\e[u9089_E010D];邉󠄍;邉\[uE010D];\[u9089_E010D];
\e[u9089_E010E];邉󠄎;邉\[uE010E];\[u9089_E010E];
\e[u908A_E0101];邊󠄁;邊\[uE0101];\[u908A_E0101];
\e[u908A_E0102];邊󠄂;邊\[uE0102];\[u908A_E0102];
\e[u908A_E0103];邊󠄃;邊\[uE0103];\[u908A_E0103];
\e[u908A_E0104];邊󠄄;邊\[uE0104];\[u908A_E0104];
\e[u908A_E0105];邊󠄅;邊\[uE0105];\[u908A_E0105];
\e[u908A_E0106];邊󠄆;邊\[uE0106];\[u908A_E0106];
\e[u908A_E0107];邊󠄇;邊\[uE0107];\[u908A_E0107];
...
.TE
.
.
.\" ------------------------------------------------------------------
.SS ハイパーリンクを使う
.\" ------------------------------------------------------------------
.
見出しをしおりやリンク先として使うには、見出しを定義するマクロに
\f(CW\*(C`pdfhref\*(C'\fP を追加します。
.
\f(CW\*(C`pdfhref\*(C'\fP は
.UR https://opensource.adobe.com/dc-acrobat-sdk-docs/acrobatsdk/pdfs/acrobatsdk_pdfmark.pdf
pdfmark
.UE
を利用するためのgroffのマクロです。
.
.PP
man.localに追加するコードの例を示します。
.
.sp 0.5
.EX
\&.am SH
\&.  pdfhref O 1 \e\e$*
\&.  pdfhref M -D \(dq\e\e$*
\&..
\&.am SS
\&.  pdfhref O 2 \e\e$*
\&.  pdfhref M -D \(dq\e\e$*
\&..
.EE
.
.PP
見出しはSHやSSマクロの引数で指定する他、マクロの次の行に置くことでも指
定できますが、このコードは引数で指定されたものしか扱えないということに
注意してください。
.
.PP
上のpdfhref Mで \-Dオプションに指定した文字列はリンク先を表わす名前に
なります。名前はURIの一部として使うことができます。見出しから名前を作
るとき、使えない文字はpdfcleanで取り除くことができますが、オリジナルの
pdfcleanはunicodeを扱うことができません。そのため名前に使えない文字を
\e*[pdfclean:magic]xx（xxは文字コード）に変換する修正を加えました。
.
（\c
.UR https://ja.wikipedia.org/wiki/パーセントエンコーディング
パーセントエンコーディング
.UE \c
も考えましたが、名前に % が使えません。）
.
pdfcleanにはスペースを \- に変換変換する修正も加えました。
（たとえば、SEE ALSOはSEE-ALSOになります。)
.
.PP
.ds PDFBOOKMARK.NAME.10 \*[PDFBOOKMARK.NAME]
.substring PDFBOOKMARK.NAME.10 0 9
.length PDFBOOKMARK.NAME.length \*[PDFBOOKMARK.NAME]
.
変換した名前はPDFBOOKMARK.NAMEに格納されるので、次のしおりを定義するま
での間、必要なら文書の中で参照することができます。たとえば、この項の見
出し「\c
.UR ハイパーリンクを使う
.UE \c
」は、長さ \n[PDFBOOKMARK.NAME.length] 文字の長い名前になります。また
始めの10文字は「\*[PDFBOOKMARK.NAME.10]...」です。
.
.PP
それなりに動いているように見えますが、しばらく使ってみようと思います。
.
.
.\" ------------------------------------------------------------------
.SS リンクテキストのはじまりと終わりを指定する
.\" ------------------------------------------------------------------
.
マンページをpdfに出力するとき \f(CW\*(C`UR\*(C'\fP と
\f(CW\*(C`UE\*(C'\fP のパラメータを
\f(CW\*(C`pdfhref\*(C'\fP に渡すことになりますが、
.
\f(CW\*(C`pdfhref\*(C'\fP のパラメータは引数で指定しなければなりま
せん。
.
\f(CW\*(C`UR\*(C'\fP と \f(CW\*(C`UE\*(C'\fP の間に置かれたテキ
ストを引数にするのは簡単ではありません。
.
そこで \f(CW\*(C`pdfhref\*(C'\fP のインタフェースを
\f(CW\*(C`UR\*(C'\fP と \f(CW\*(C`UE\*(C'\fP に合わせて、
.
はじまりと終わりを \f(CW\*(C`pdfhref -S\*(C'\fP と
\f(CW\*(C`pdfhrefend\*(C'\fP で指定します。
.
これらは、
.B groff
のpdfドライバ
.BR gropdf (1)
の
.BI "\[rs]X'pdf: markstart " "/ANN definition" '
と
.B \[rs]X'pdf: markend'
に対応します。
.
.\" ------------------------------------------------------------------
.SS 日本語フォントで text.enc を使う?
.\" ------------------------------------------------------------------
.
text.encはテキストフォントのエンコーディング (グリフの名前と番号、番号
はGIDのようなもの) を定義します。
.
番号は0から255、または0から65535の値をとります。\f(CW\eN'番号'\fP は、
現在のフォントで指定した番号のグリフをタイプセットします。
.
.PP
groffパッケージの欧文のフォントは、作成時のエンコーディイングオプショ
ンにtext.encが指定されています。
.
(font/devps/generate/Makefileを参照のこと)
.
.PP
日本語のフォントでもtext.encを指定する方がいいでしょうか？以前はNoだっ
たかもしれませんが、いまはYesかもしれません。
.
.PP
日本語のグリフをタイプセットするためにspecialリクエストを使って、欧文
のフォントにないグリフを日本語のフォントで検索するように設定していると
き、text.encに定義されているグリフ (欧文のグリフ) は欧文のフォントで見
付かります。(検索には順番があります。)
.
このような使い方をするとき、日本語のフォントの作成にtext.encを指定する
必要はありません。
.
.PP
最近のNotoやその派生フォントは、必要なグリフを1つのフォントに格納しよ
うとしています。それは、specialリクエストで複数のフォントを組み合わせ
る必要を無くしたり、デフォルトのフォントに日本語のフォントを指定できる
ようにするなど、利用者にやさしいものだと思います。
.
しかし、日本語のフォントでもtext.encが必要になり、それによって
ToUnicodeが出力され、pdfのファイルサイズを大きくします。
.
.PP
デフォルトのToUnicodeは、text.encに定義された合字のグリフ（\c
.ie c\N'140' .nop \*[lq]\N'140'\*[rq]\c
.el .nop \*[lq]fi\*[rq]\c
、
.ie c\N'141' .nop \*[lq]\N'141'\*[rq]
.el .nop \*[lq]fl\*[rq]
など）、区別の難しいグリフ（\c
.ie c\N'173' .nop \*[lq]\N'173'\*[rq]
.el .nop \*[lq]-\*[rq]
minusと
.ie c\N'45' .nop \*[lq]\N'45'\*[rq]
.el .nop \*[lq]-\*[rq]
hyphen）に適切なテキストを与えます。
.
たとえばpdfのコピペで働きます。
.
.UR https://golden-lucky.hatenablog.com/entry/2019/12/05/171340
PDFから「使える」テキストを取り出す（第5回）
.UE 、
.UR https://github.com/trueroad/pdf-rm-tuc/blob/master/README.ja.md
PDF から ToUnicode CMap を削除するツール
.UE \c
に興味深い説明があります。
.
.PP
日本語のフォントでtext.encを使う使わないをfont*.mkで指定する方法を示し
ます。
.
.EX
\&$ make -f font.mk clean install   # 日本語のフォントにtext.encを使う
\&$ TEXT_ENC= make -f font.mk clean install   # 〜使わない
.EE
.
.PP
manコマンドでgroff(1)のpdfを出力するとき、たとえば M (明朝) を欧文のグ
リフとして指定するには、次のコマンドを実行します。(ubuntu)
.
.EX
\&$ MANROFFOPT=-fM man -Tpdf -L ja groff >a.pdf
.EE
.
.PP
(あとで)
.UR https://helpx.adobe.com/jp/fonts/kb/postscript-type-1-fonts-end-of-support.html
PostScript Type\~1 フォントのサポート終了
.UE
(\c
.UR https://helpx.adobe.com/fonts/kb/postscript-type-1-fonts-end-of-support.html
原文
.UE )
.
.
.bp
.\" ------------------------------------------------------------------
.SS 両端揃えの比較
.\" ------------------------------------------------------------------
.fam T
.UR https://www.aozora.gr.jp/cards/001779/card56646.html
心理試験（青空文庫 図書カード：No.56646）
.UE
.
をmodeを指定して処理し、スペースの配置を確かめます。
.
.nr pp:debug.bak \n[pp:debug]
.nr pp:debug 1
.PP
.B
1. 日本語の行の継続で取り除かれるスペースを見る（mode 32）
.
.ll 30m
.PP
.\" pp-ja 32
例えば、Automatograph等の力を借りて、手の微細な動きを発見する方法。あ
る手段によって眼球の動き方を確める方法。Pneumographによって呼吸の深浅
遅速を計る方法。Sphygmographによって脈搏の高低遅速を計る方法。
Plethysmographによって四肢の血量を計る方法。Galvanometerによって掌の
微細なる発汗を発見する方法。膝の関節を軽く打って生ずる筋肉の収縮の多少
を見る方法、其他これらに類した種々様々の方法がある。
.\" pp-ja
.ll
.
.PP
.\"B 2. 行を跨ぐ日本語の文をつなぐ。 約物のスペースを補正に使う （mode 1）
.B
2. 行を跨ぐ日本語の文をつなぐ。約物のスペースを補正に使う（mode 1）
.
.ll 30m
.PP
.\" pp-ja 1
例えば、Automatograph等の力を借りて、手の微細な動きを発見する方法。あ
る手段によって眼球の動き方を確める方法。Pneumographによって呼吸の深浅
遅速を計る方法。Sphygmographによって脈搏の高低遅速を計る方法。
Plethysmographによって四肢の血量を計る方法。Galvanometerによって掌の
微細なる発汗を発見する方法。膝の関節を軽く打って生ずる筋肉の収縮の多少
を見る方法、其他これらに類した種々様々の方法がある。
.\" pp-ja
.ll
.
.PP
.\".B 3. 上記 2. に加え、 和文と欧文の境界、 および字間にスペースを補う （mode 7）
.B
3. 上記2.に加え、和文と欧文の境界、および字間にスペースを補う（mode 7）
.
.ll 30m
.PP
.\" pp-ja 7
例えば、Automatograph等の力を借りて、手の微細な動きを発見する方法。あ
る手段によって眼球の動き方を確める方法。Pneumographによって呼吸の深浅
遅速を計る方法。Sphygmographによって脈搏の高低遅速を計る方法。
Plethysmographによって四肢の血量を計る方法。Galvanometerによって掌の
微細なる発汗を発見する方法。膝の関節を軽く打って生ずる筋肉の収縮の多少
を見る方法、其他これらに類した種々様々の方法がある。
.\" pp-ja
.ll
.
.nr pp:debug \n[pp:debug.bak]
.
.PP
誤りや改善のご指摘がありましたら、お気軽にどうぞ。
.
