.\" -*- nroff -*-
.
.TH SAMPLE 7
.\"ss 12
.ds dg "\v[-0.4m]\s-3\[dg]\s+3\v[+0.4m]\""
.ds dd "\v[-0.4m]\s-3\[dd]\s+3\v[+0.4m]\""
.ds la \[u3008]
.ds ra \[u3009]
.ds C` \f(CW\s-1
.ds C' \s+1\fP
.
.am1 EX
.in +1m
.nr VS_EX (\\n[PS] * 120 / 100)
.vs \\n[VS_EX]u
.ps -1
..
.am1 EE
.ps
.in
..
.
.
.\" ------------------------------------------------------------------
.SH NAME
.\" ------------------------------------------------------------------
.
sample \- Groff と日本語
.
.\" ------------------------------------------------------------------
.SH SYNOPSYS
.\" ------------------------------------------------------------------
.
.EX
groff -KUTF-8 -mja -man ./sample.7 >a.ps
.EE
.
.\" ------------------------------------------------------------------
.SH DESCRIPTION
.\" ------------------------------------------------------------------
.
.\" ------------------------------------------------------------------
.SS 日本語マンページのメモ
.\" ------------------------------------------------------------------
.
FreeBSD の日本語のマンページ groff(7) を開くと中に次のようなメモがあります。
.
.PP
.EX
\&.\\" nroff の justification をオフにする. justification は, 日本語に似合わない.\""
\&.na
\&.\\" ハイフネーションをオフにする.\""
\&.hy 0
.EE
.
.PP
groff で justification を有効にして日本語を処理すると、所々に大きなス
ペースのある少し読み難い出力になることがあります。
.
.PP
感じ方は人それぞれだと思いますが、読み難いと疲れるので、groff の前処理
とマクロを利用して補正してみようと思います。
.
.
.\" ------------------------------------------------------------------
.SS メモの行を無効に、 それなりに
.\" ------------------------------------------------------------------
.
とりあえず、マンページに追加された上のメモに書かれた行 \*(C`na\*(C' や
\*(C`hy\~0\*(C' を無効にします。
.
.PP
.EX
\&.if n .na
\&.if n .hy 0
.EE
.
.PP
同様のメモは、たとえば debian の
.pdfhref W -D https://manpages.debian.org/buster/manpages-ja/groff.7.ja.html -- \
groff(7)
.
にはありません。ubuntu は \*(C`ad l\*(C' を使っています。
いろいろありそうです。そういうわけで、それなりに修正します。
.
.\" ------------------------------------------------------------------
.SS prepro の使い方は
.\" ------------------------------------------------------------------
.
DESC ファイルの prepro 行を使って troff に前処理プログラムを追加します。
DESC ファイルの説明は groff_font(5) にあります。例を示します。
.
.PP
.EX
\&prepro /usr/local/bin/pre-gropdf.pl
.EE
.
.PP
prepro(1) はありませんが、groff(1) に groff \-V を使えば起動するコマン
ド（パイプライン）が分ることが説明されています。ある程度のことは試して
調べられそうです。
.
.PP
prepro はその標準出力が troff の標準入力になるように troff とパイプで
つなぎます。
.
.PP
prepro の入力は、troff の入力ファイルとしてコマンドラインに指定されて
いるときはそれを、何も指定されていなければ標準入力を使います。
.
.PP
prepro のコマンドラインには出力ドライバのオプションも渡されます。出力
ドライバとの協調に役立ちますが、使わなくてもパースする必要があります。
.
.\" ------------------------------------------------------------------
.SS 日本語の改行を取り除く (PREPRODEBUG=8)
.\" ------------------------------------------------------------------
.
改行は空白と同様に扱われます。行末から行頭にかけて日本語の文字（平仮名、
片仮名、漢字）が続くとき、改行を取り除いて次の行とつなぎます。抑止する
には行頭に \*(lq.\*(rq を置きます。
.
.PP
結果は環境変数 \*(C`PREPRODEBUG=8\*(C' で確かめます。
.\" \*(lq\fB\s-2\[u23CE]\s+2\fP\*(rq
.
.PP
.EX
env PREPRODEBUG=8 groff -Tpdf -man -mja -Kutf8 sample.7 > sample.pdf
.EE
.
.\"| gs -sDEVICE=pdfwrite -dPrinted=false -dNOPAUSE -dQUIET -dBATCH -sOutputFile=- -
.
.\" ------------------------------------------------------------------
.SS 約物のスペースを groff の伸縮可能なスペースと組合せる
.\" ------------------------------------------------------------------
.
約物に含まれるスペースが調整に使えるように groff のスペース（伸縮可能）
と取り替えます。イメージを示します。
.
.PP
.IP \(bu 4
\[bv]\z。\h'1m'\[bv] \(-> \[bv]\z。\h'0.5m'\[bv] + \h'0.25m'\[u2423]
.IP \(bu 4
\[bv]\z、\h'1m'\[bv] \(-> \[bv]\z、\h'0.5m'\[bv] + \h'0.25m'\[u2423]
.IP \(bu 4
\[bv]\h'0.5m'\Z'\&（'\h'0.5m'\[bv] \(-> \h'0.25m'\z\[u2423]\h'1.25m' +
\[bv]\Z'\&（'\h'0.5m'\[bv]
.IP \(bu 4
\[bv]\z）\h'1m'\[bv] \(-> \[bv]\z）\h'0.5m'\[bv] + \h'0.25m'\[u2423]
.
.
.\" ------------------------------------------------------------------
.SS 約物のスペースを確かめる
.\" ------------------------------------------------------------------
.
約物のスペース（アキ）を確かめ、必要なら \*(C`.ss\*(C' で調整します。
.
.\" pp-ja 3
.TP 12
.B それなり
\c
■■■。■■■\[bv]■■■。■■■\[bv]■■■。■■■\[bv]■■■。■■■\[bv]
.
.TP
.gcolor grey
.B ベタ
\c
■■■。\&■■■\[bv]■■■。\&■■■\[bv]■■■。\&■■■\[bv]■■■。\&■■■\[bv]
.gcolor
.
.TP
.B 四分
\c
■■■\z。\h'+0.75m'■■■\[bv]■■■\z。\h'+0.75m'■■■\[bv]■■■\z。\h'+0.75m'■■■\[bv]■■■\z。\h'+0.75m'■■■\[bv]
.
.TP
.gcolor grey
.B 二分
\c
■■■\z。\h'+1m'■■■\[bv]■■■\z。\h'+1m'■■■\[bv]■■■\z。\h'+1m'■■■\[bv]■■■\z。\h'+1m'■■■\[bv]
.gcolor
.
.\" pp-ja
.
.PP
\*(C`.ss 12\*(C' で「それなり」の行と「四分」の行の長さがほぼ同じ長さ
になります。約物のアキを欧文の語間に使うスペースと兼用したので、調整す
るときは欧文の語間に注意してください。
.
.\" ------------------------------------------------------------------
.SS 連続する約物を補正する (PREPRODEBUG=9)
.\" ------------------------------------------------------------------
.
.pdfhref W -D https://www.w3.org/TR/jlreq/ja/ -- \
  日本語組版処理の要件 （日本語版） W3C 技術ノート 2012年\:4月\:3日
.
\c
「3.1.4 始め括弧類，終わり括弧類，読点類，句点類及び中点類が連続する場
合の配置方法」の例を示します。
.
.PP
.IP \[u2460]  4
句読点の後ろに終わり括弧類が連続
.br
…である。」この…
.
.IP \[u2461]  4
終わり括弧類の後ろに句読点が連続
.br
…である）。この…
.
.IP \[u2462]  4
読点類の後ろに始め括弧類が連続
.br
…である、「この…
.
.IP \[u2463]  4
終わり括弧類の後ろに始め括弧類が連続
.br
…である」「この…
.
.IP \[u2464]  4
始め括弧類の後ろに始め括弧類が連続
.br
…である「『この…
.
.IP \[u2465]  4
終わり括弧類の後ろに終わり括弧類が連続
.br
…である）」この…
.
.IP \[u2466]  4
括弧類と中点類が連続
.br
…「編集」・「校正」…
.
.PP
役物のスペースの配置は、環境変数 \*(C`PREPRODEBUG=9\*(C' で確かめます。
.
.
.\" ------------------------------------------------------------------
.SS 文字間に伸縮可能なスペースを挟む (PREPRODEBUG=11)
.\" ------------------------------------------------------------------
.
伸縮可能なスペースは node.cpp に stretchable zero-width space not
implemented yet というコメントがありますから、とりあえずマクロで実装し
ます。期待して待ちましょう。
.
.PP
文字間に \*(C`.zwsp\*(C' を挟みます。たとえば「お早う」は次のとおり。
.
.PP
.EX
\&お\\c
\&.zwsp
\&早\\c
\&.zwsp
\&う\\c
.EE
.
.PP
結果は環境変数 \*(C`PREPRODEBUG=11\*(C' で確かめます。
.
.PP
注意、この方法は \*(C`.TP\*(C' の直後の行（ラベル）に使うことができません。
.
.
.\" ------------------------------------------------------------------
.SS プロポーショナルフォント（もどき）を作る
.\" ------------------------------------------------------------------
.
約物の字体を調整します。フォントを直すのは大変なので、groff で調整しま
す。サンプルの ps.local の一部を示します。
.
.PP
.EX
\&.\\" A.6 Full stops (cl-06)\""
\&.if (\\w'\\\&[u3002]' > 0.8m) .char \\\&[u3002] \\\&[u3002]\\h'-0.5m'\\" 。\""
\&.if (\\w'\\\&[uFF0E]' > 0.8m) .char \\\&[uFF0E] \\\&[uFF0E]\\h'-0.5m'\\" ．\""
.EE
.
.PP
ここで使用したフォントは、
.pdfhref W -D https://github.com/3846masa/sauce-han-fonts -- \
醤ノ角ゴシック (ひしおのかくごしっく) と醤ノ明朝 (ひしおのみんちょう)
.
です。他のフォントでは別の調整が必要になるかもしれません。
.
.sp 999
.\" ------------------------------------------------------------------
.SS 両端揃えの比較
.\" ------------------------------------------------------------------
.
.pdfhref W -D https://www.aozora.gr.jp/cards/001779/card56646.html -- \
心理試験（青空文庫 図書カード：No.56646）
.
を両端揃えの比較に使います。
.
.ll 30m
.PP
.\" pp-ja 0
.ti -1
.B 1. 改行を取り除く
.br
例えば、Automatograph 等の力を借りて、手の微細な動きを発見する方法。あ
る手段によって眼球の動き方を確める方法。Pneumograph によって呼吸の深浅
遅速を計る方法。Sphygmograph によって脈搏の高低遅速を計る方法。
Plethysmograph によって四肢の血量を計る方法。Galvanometer によって掌の
微細なる発汗を発見する方法。膝の関節を軽く打って生ずる筋肉の収縮の多少
を見る方法、其他これらに類した種々様々の方法がある。
.\" pp-ja
.PP
.\" pp-ja 1
.ti -1
.B 2. 約物のスペースを調整する
.br
例えば、Automatograph 等の力を借りて、手の微細な動きを発見する方法。あ
る手段によって眼球の動き方を確める方法。Pneumograph によって呼吸の深浅
遅速を計る方法。Sphygmograph によって脈搏の高低遅速を計る方法。
Plethysmograph によって四肢の血量を計る方法。Galvanometer によって掌の
微細なる発汗を発見する方法。膝の関節を軽く打って生ずる筋肉の収縮の多少
を見る方法、其他これらに類した種々様々の方法がある。
.\" pp-ja
.PP
.\" pp-ja 3
.ti -1
.B 3. 約物のスペースと文字間を調整する
.br
例えば、Automatograph 等の力を借りて、手の微細な動きを発見する方法。あ
る手段によって眼球の動き方を確める方法。Pneumograph によって呼吸の深浅
遅速を計る方法。Sphygmograph によって脈搏の高低遅速を計る方法。
Plethysmograph によって四肢の血量を計る方法。Galvanometer によって掌の
微細なる発汗を発見する方法。膝の関節を軽く打って生ずる筋肉の収縮の多少
を見る方法、其他これらに類した種々様々の方法がある。
.\" pp-ja
.ll
.
.sp
.PP
誤りや改善のご指摘がありましたら、お気軽にどうぞ。

