.\" -*- nroff -*-
.
.TH SAMPLE 7
.\"ss 12
.ds dg "\v[-0.4m]\s-3\[dg]\s+3\v[+0.4m]\""
.ds dd "\v[-0.4m]\s-3\[dd]\s+3\v[+0.4m]\""
.ds la \[u3008]
.ds ra \[u3009]
.
.de SH2
.SH \F[G]\\$*\F[]
..
.de SS2
.SS \F[G]\\$*\F[]
..
.am1 EX
.in +1m
.nr VS_EX (\\n[PS] * 120 / 100)
.vs \\n[VS_EX]u
.ps -1
..
.am1 EE
.ps
.in
..
.
.
.\" ------------------------------------------------------------------
.SH2 NAME
.\" ------------------------------------------------------------------
.
sample \- Groff と日本語
.
.
.\" ------------------------------------------------------------------
.SH2 SYNOPSYS
.\" ------------------------------------------------------------------
.
.EX
groff -KUTF-8 -mja -man ./sample.7 >a.ps
.EE
.
.\" ------------------------------------------------------------------
.SH2 DESCRIPTION
.\" ------------------------------------------------------------------
.
.\" ------------------------------------------------------------------
.SS2 日本語マンページのメモ
.\" ------------------------------------------------------------------
.
日本語のマンページを開くと中に次のようなメモがあります。
.
.PP
.EX
\&.\\" nroff の justification をオフにする. justification は, 日本語に似合わない.
\&.na
\&.\\" ハイフネーションをオフにする.
\&.hy 0
.EE
.
.PP
ジャスティファイ（箱組み）は、スペースを調整して両端を揃えます。スペー
スはわかち書きを使う言語では語の区切りにありますが、日本語はそうではあ
りません。日本語はスペースを使わずに文章を書くことができます。そのため
ジャスティファイが整形結果を乱すことがあります。
.
.
.\" ------------------------------------------------------------------
.SS2 日本語でジャスティファイを使う
.\" ------------------------------------------------------------------
.
日本語のジャスティファイは、
.UR https://\:www.w3.org/\:TR/\:jlreq/\:ja/
日本語組版処理の要件（日本語版）
W3C 技術ノート 2012年\:4月\:3日
.UE
「3.8 行の調整処理」に説明されています。ここでは、その中の空きを詰める
処理と空ける処理について、前者にプロポーショナルフォント、後者に伸縮可
能なスペースを使います。
.
.PP
それからジャスティファイを無効にするために追加された \F[C]na\F[] や
\F[C]hy\~0\F[] を nroff に制限します。
.
.PP
.EX
\&.if n .na
\&.if n .hy 0
.EE
.
.
.\" ------------------------------------------------------------------
.SS2 日本語の字間に伸縮可能なスペースを挟む（空ける処理）
.\" ------------------------------------------------------------------
.
.ig
伸縮可能なスペースは node.cpp に stretchable zero-width space not
implemented yet というコメントがありますから、とりあえずマクロで実装し
ます。期待して待ちましょう。
..
.
.PP
字間のスペースは、文字の後に\F[C]\[rs]c\F[] を置いて改行を取り除き、行
を改め、伸縮可能なスペースをマクロで挟みます。「お早うございます」を例
に示します。
.
.PP
.EX
\&お\\c
\&.zwsp
\&早\\c
\&.zwsp
\&う\\c
\&...
\&\\"（以下省略）\""
.EE
.
.ig
.PP
マクロの引数に使うことができないので、見出しは少し窮屈になると思います。
しかし、groff（troff）を変更する必要がありません。
..
.
.PP
書き換えは groff の ps ドライバ grops のプリプロセッサに実装します。他
にも禁則処理や行番号の補正があります。詳細はコードを参照してください。
.
.
.\" ------------------------------------------------------------------
.SS2 日本語の改行を取り除く
.\" ------------------------------------------------------------------
.
わかち書きを使う言語では改行も語の区切りのひとつです。そのままにすると
空白になります。行末から行頭にかけて日本語の文字（平仮名、片仮名、漢字）
が続くときは \F[C]\[rs]c\F[] で改行を無効にして、行をつなぎます。字間
にゼロ幅スペースを挟むように行末〜行頭間にも挟みます。
.
.PP
もし不都合なら間に \*(lq.\*(rq ではじまる行（\*(lq.\*(rq のみで十分）
を置いてください。
.
.\" ------------------------------------------------------------------
.SS2 全角の約物を伸縮可能なスペースと組合せる（詰める処理と空ける処理）
.\" ------------------------------------------------------------------
.
約物（句読点や括弧など）の字体に含まれるスペースをプロポーショナルフォ
ントを使って取り除きます。そして伸縮可能なスペースと組合せます。イメー
ジを示します。
.
.PP
.IP \(bu 4
\[bv]\z。\h'1m'\[bv] \(-> \[bv]\z。\h'0.5m'\[bv] + \h'0.25m'\[u2423]
.IP \(bu 4
\[bv]\z、\h'1m'\[bv] \(-> \[bv]\z、\h'0.5m'\[bv] + \h'0.25m'\[u2423]
.IP \(bu 4
\[bv]\h'0.5m'\Z'\&（'\h'0.5m'\[bv] \(-> \h'0.25m'\z\[u2423]\h'1.25m' +
\[bv]\Z'\&（'\h'0.5m'\[bv]
.IP \(bu 4
\[bv]\z）\h'1m'\[bv] \(-> \[bv]\z）\h'0.5m'\[bv] + \h'0.25m'\[u2423]
.
.
.\" ------------------------------------------------------------------
.SS2 連続する約物を補正する
.\" ------------------------------------------------------------------
.
日本語組版処理の要件（日本語版）「3.1.4 始め括弧類，終わり括弧類，読点
類，句点類及び中点類が連続する場合の配置方法」の補正結果を示します。
.
.IP \[u2460]  4
句読点の後ろに終わり括弧類が連続
.br
.\" pp-ja 1
…である。」この…
.br
.\" pp-ja
.if (\V[DEBUG] > 0) \{\
.\" pp-ja 9
…である。」この…	DEBUG
.br
.\" pp-ja
.\}
.
.IP \[u2461]  4
終わり括弧類の後ろに句読点が連続
.br
.\" pp-ja 1
…である）。この…
.br
.\" pp-ja
.if (\V[DEBUG] > 0) \{\
.\" pp-ja 9
…である）。この…	DEBUG
.br
.\" pp-ja
.\}
.
.IP \[u2462]  4
読点類の後ろに始め括弧類が連続
.br
.\" pp-ja 1
…である、「この…
.br
.\" pp-ja
.if (\V[DEBUG] > 0) \{\
.\" pp-ja 9
…である、「この…	DEBUG
.br
.\" pp-ja
.\}
.
.IP \[u2463]  4
終わり括弧類の後ろに始め括弧類が連続
.br
.\" pp-ja 1
…である」「この…
.br
.\" pp-ja
.if (\V[DEBUG] > 0) \{\
.\" pp-ja 9
…である」「この…	DEBUG
.br
.\" pp-ja
.\}
.
.IP \[u2464]  4
始め括弧類の後ろに始め括弧類が連続
.br
.\" pp-ja 1
…である「『この…
.br
.\" pp-ja
.if (\V[DEBUG] > 0) \{\
.\" pp-ja 9
…である「『この…	DEBUG
.br
.\" pp-ja
.\}
.
.IP \[u2465]  4
終わり括弧類の後ろに終わり括弧類が連続
.br
.\" pp-ja 1
…である）」この…
.br
.\" pp-ja
.if (\V[DEBUG] > 0) \{\
.\" pp-ja 9
…である）」この…	DEBUG
.br
.\" pp-ja
.\}
.
.IP \[u2466]  4
括弧類と中点類が連続
.br
.\" pp-ja 1
…「編集」・「校正」…
.br
.\" pp-ja
.if (\V[DEBUG] > 0) \{\
.\" pp-ja 9
…「編集」・「校正」…	DEBUG
.br
.\" pp-ja
.\}
.
.PP
役物のスペースの配置を確かめるには、環境変数
.SM DEBUG
に、\*(lq0\*(rq 以外の値を指定して、もう一度 ps を作り直してください。
.PP
.EX
DEBUG=1 groff -KUTF-8 -mja -man ./sample.7
.EE
.
.ig
.PP
.UR https://\:www.gnu.org/\:software/\:groff/\:manual/\:html_node/\:Ligatures-and-Kerning.html
Ligatures and Kerning
.UE
も試しましたが、日本語の約物には使えませんでした。
確か unicode の文字には使えない、といった類のエラーが出力されました。
..
.
.\" ------------------------------------------------------------------
.SS2 プロポーショナルフォント（もどき）を作る
.\" ------------------------------------------------------------------
.
約物の字体を調整します。フォントを直すのは大変なので、groff で調整しま
す。サンプルの ps.local の一部を示します。
.
.PP
.EX
\&.\\" A.6 Full stops (cl-06)\""
\&.if (\\w'\\\&[u3002]' > 0.8m) .char \\\&[u3002] \\\&[u3002]\\h'-0.5m'\\" 。\""
\&.if (\\w'\\\&[uFF0E]' > 0.8m) .char \\\&[uFF0E] \\\&[uFF0E]\\h'-0.5m'\\" ．\""
.EE
.
.PP
確認に使用したフォントを示します。
.IP \(bu 4
.UR https://\:github.com/\:3846masa/\:sauce-han-fonts
醤ノ角ゴシック (ひしおのかくごしっく) と醤ノ明朝 (ひしおのみんちょう)
.br
.UE
.IP \(bu 4
.UR http://\:jikasei.me/\:font/\:genshin/
源真ゴシック (げんしんゴシック)
.br
.UE
.
.
.\" ------------------------------------------------------------------
.SS2 伸縮可能なスペースをエスケープで実装する（実験）
.\" ------------------------------------------------------------------
.
マクロで実装した伸縮可能なスペースは、上の例「おはようございます」のよ
うに複数行に展開されるので、たとえば tbl の作る表を乱します。
.
.ig
回避するために fc リクエストを日本語の補正の判断材料にして伸縮可能なス
ペースの追加を抑止します。
..
マクロの引数に使えないので、見出しが窮屈になります。
.
これらは伸縮可能なスペースをエスケープを使って実装することで改善できま
す。
.
.PP
次の例は ss リクエストを未使用のエスケープ j に割り当ています。
.
.IP \F[C]\[rs]j[0]\[u2423]\[rs]j[]\F[] 16
ゼロ幅スペース（ブレーク可能）
.IP \F[C]\[rs]j[0]\[rs]~\[rs]j[]\F[] 16
ゼロ幅スペース（ブレーク不可）
.IP \F[C]\[rs]j[4]\[u2423]\[rs]j[]\F[] 16
四分アキ（伸ばされることを考慮して小さめ）
.
.PP
エスケープで実装すると行番号が狂わなくなりますが、パッチはパッチでしか
ないので、後で考えようと思います。（escape-j.patch）
.
.ig
.\" ------------------------------------------------------------------
.SS2 約物のスペースを確かめる
.\" ------------------------------------------------------------------
.
約物のスペースの大きさを確かめます。
.
.TP
.B 確認
■■■。■■■\[bv]■■■。■■■\[bv]■■■。■■■\[bv]■■■。■■■\[bv]
.
.TP
.gcolor grey
.B ベタ
■■■。\&■■■\[bv]■■■。\&■■■\[bv]■■■。\&■■■\[bv]■■■。\&■■■\[bv]
.
.TP
.B 四分
■■■\z。\h'+0.75m'■■■\[bv]■■■\z。\h'+0.75m'■■■\[bv]■■■\z。\h'+0.75m'■■■\[bv]■■■\z。\h'+0.75m'■■■\[bv]
.
.TP
.B 二分
■■■\z。\h'+1m'■■■\[bv]■■■\z。\h'+1m'■■■\[bv]■■■\z。\h'+1m'■■■\[bv]■■■\z。\h'+1m'■■■\[bv]
.gcolor
.
.
.PP
約物のスペースの大きさは、ss リクエストで調整できます。デフォルトでは
「確認」と「四分」の行が同じくらいの長さになります。
..
