#!perl
requires 'perl', '5.010001';

on 'test' => sub {
    requires 'Test::More', '0.98';
    requires 'Perl6::Slurp';
};

 'Moo';
requires 'Types::Standard';
requires 'Mojolicious::Lite';
requires 'URI::Encode';
requires 'File::Path';
requires 'File::Spec::Functions';
requires 'File::Basename';
